config/routes.rb
Rails.application.routes.draw do
  resources :submissions
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/submission.rb
class Submission < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/submissions_controller.rb
class SubmissionsController < ApplicationController
  # We won't enforce same-origin when checking authenticity
  self.forgery_protection_origin_check = false

  # Don't render layout if the request is XHR
  layout proc { false if request.xhr? }

  before_action :set_submission, only: [:show, :edit, :update, :destroy]
  before_action :new_submission, only: [:new, :index, :create]
  before_action :all_submissions, only: [:new, :index, :create]

  after_action :all_submissions, only: [ :create ]
  after_action :new_submission, only: [ :create ]

  # GET /submissions
  # GET /submissions.json
  def index
  end

  # GET /submissions/1
  # GET /submissions/1.json
  def show
  end

  # GET /submissions/new
  def new
  end

  # GET /submissions/1/edit
  def edit
  end

  # POST /submissions
  # POST /submissions.json
  def create
    @submission = Submission.new(submission_params)

    respond_to do |format|
      if @submission.save
        format.html { redirect_to @submission, notice: 'Submission was successfully created.' }
        format.js { }
        format.json { render :show, status: :created, location: @submission }
      else
        format.html { render :new }
        format.js { }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /submissions/1
  # PATCH/PUT /submissions/1.json
  def update
    respond_to do |format|
      if @submission.update(submission_params)
        format.html { redirect_to @submission, notice: 'Submission was successfully updated.' }
        format.json { render :show, status: :ok, location: @submission }
      else
        format.html { render :edit }
        format.json { render json: @submission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /submissions/1
  # DELETE /submissions/1.json
  def destroy
    @submission.destroy
    respond_to do |format|
      format.html { redirect_to submissions_url, notice: 'Submission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_submission
      @submission = Submission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def submission_params
      params.require(:submission).permit(:word)
    end

    def new_submission
      @new_submission = @submission = Submission.new
    end

    def all_submissions
      @submissions = Submission.all
    end

    # This overrides a method found in
    # lib/action_controller/metal/request_forgery_protection.rb
    #
    # The method I'm overriding would not strip off the hostname and protocol
    # portion of the action_path, and when making my first request to the
    # remote server, the protocol and hostname would be part of the path but
    # then submitting the form back to the remote server would not include
    # the hostname and protocol and so the authenticity tokens would
    # appear different.
    #
    # I can't tell if this is a feature or a bug since I'm clearly trying to
    # do things via CORS that should not be done
    def normalize_action_path(action_path)
      logger.debug URI.parse(action_path).inspect
      URI.parse(action_path).path.to_s.chomp('/')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/submissions_helper.rb
module SubmissionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TestCors2</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/submissions/_form.html.erb
<!-- I had to modify the URL for the form so it points to submission_url rather than submisttion_path in order to send submissions back to the second server -->
<%= form_for(submission, url: submission.new_record? ? submissions_url(submission) : submission_url(submission), remote: true) do |f| %>
  <% if submission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(submission.errors.count, "error") %> prohibited this submission from being saved:</h2>

      <ul>
      <% submission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :word %>
    <%= f.text_area :word %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/submissions/_index.html.erb
<table>
  <thead>
    <tr>
      <th>Word</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @submissions.each do |submission| %>
      <tr>
        <td><%= submission.word %></td>
        <td><%= link_to 'Show', submission %></td>
        <td><%= link_to 'Edit', edit_submission_path(submission) %></td>
        <td><%= link_to 'Destroy', submission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/submissions/create.js.erb
$("#submissions").html("<%= escape_javascript(render 'index') %>");
$("#submission_form").html("<%= escape_javascript(render 'form', submission: (@new_submission || @submission)) %>");

app/views/submissions/edit.html.erb
<h1>Editing Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Show', @submission %> |
<%= link_to 'Back', submissions_path %>

app/views/submissions/index.html.erb
<% if request.env["SERVER_PORT"].to_i != 8000 -%>

<!-- We ontly want to render this section when we're dealing with the remote server -->

<p id="notice"><%= notice %></p>

<h1>Port <%=h request.env["SERVER_PORT"] %> Submissions: <%= request.xhr?.inspect %></h1>

<div id="submissions">
  <%= render 'index' %>
</div>

<br>

<div id="submission_form">
  <%= render 'form', submission: @submission %>
</div>

<hr>
<% end %>

<% if request.env["SERVER_PORT"].to_i == 8000 -%>
<!-- And we only want to render this section when we visit the first server -->
  <div id="remote_form" />
  <script type="text/javascript" charset="utf-8">
    $(document).on('page:change', function() {
      $.ajaxPrefilter( function( options, originalOptions, jqXHR ) {
        // This will catch any AJAX request and attempt to make it use CORS
        // However, setting crossDomain to true causes the X-Requested-With
        // header to be dropped, meaning that Rails sets request.xhr? to false
        // which isn't what I want.
        options.crossDomain = true;
        options.headers = {'X-Requested-With': 'XMLHttpRequest'};

        // We want to pass "credentials" which really means the session cookie
        options.xhrFields = {
          withCredentials: true
        };
      });

      // This just fetches the list and form from the remote server
      $.ajax({
        url: 'http://site2.127.0.0.1.xip.io/submissions',
        type: 'GET',
        dataType: 'html',
        success: function(data) {
          $('#remote_form').append(data);
        },
        error: function(xhr, message) {
          console.log(xhr);
          console.log(message);
        }
      });
    });
  </script>
<% end %>

app/views/submissions/index.js.erb
$("#submissions").html("<%= escape_javascript(render 'index') %>");
$("#submission_form").html("<%= escape_javascript(render 'form', submission: @submission) %>");

app/views/submissions/new.html.erb
<h1>New Submission</h1>

<%= render 'form', submission: @submission %>

<%= link_to 'Back', submissions_path %>

app/views/submissions/new.js.erb
$("#submissions").html("<%= escape_javascript(render 'index') %>");
$("#submission_form").html("<%= escape_javascript(render 'form', submission: @submission) %>");

app/views/submissions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Word:</strong>
  <%= @submission.word %>
</p>

<%= link_to 'Edit', edit_submission_path(@submission) %> |
<%= link_to 'Back', submissions_path %>